### ISSUE TITLE
Delete Organisation metadata

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/avni-webapp#787]
### Need:
Currently when some organisation wants to try out Avni for self-service purpose(with or without training), our sales team creates an organisation for them and creates a user in the organisation and shares the login details of the created user with them. Say they configured something incorrectly and want to try out from beginning or want to share the same organisation to someone else within the org to explore from scratch, currently sales team need to create multiple such trial orgs since 'DELETE ALL DATA' in 'Organisation Details' doesn't work as expected.

### As is:
- Currently only deleting of transactional data works correctly.
- When 'Delete Everything' is checked, sometimes shows errors like below since deleting of everything is not handled:
![Image](https://github.com/user-attachments/assets/964efdb6-f1f8-4b78-97a3-f81651023f49)

### AC:
- When only 'Delete all metadata...except admin..' is checked and clicked on Delete, everything should be deleted except things configured under Admin tab(should be retained after deletion)
- When 'Delete admin configurations' is also checked along with the above, the organisation should be clean(also  internal tables like batch_job tables etc., need to be deleted) like it was newly created except for users in the Administrators group. The user should be able to proceed with any configuration after this.
- ~When 'Delete admin configurations' is alone checked(without deletion of metadata), things under Admin tab should be deleted(also  internal tables like batch_job tables etc.,) and metadata information should be retained.~(Not valid, as we cannot delete AddressLevelTypes which are required in metadata)
- When both the checkboxes are not checked, only transactional data should get deleted.
- After the above action, anything(default dashboard or part of organisation config or groups, etc.,) that comes as default with organisation creation should be retained.
![Image](https://github.com/user-attachments/assets/6321532c-fe8a-4d25-9fd9-0fb691cca260)

### Technical inputs:
Some of the tables for which deletion not taken care of:
catchment_address_mapping, catchment, location_location_mapping, address_level, users, decision_concept, documentation related tables, dashboard_filter, external_system_config, etc.,

## Old: Ignore
- Org config is deleted. This causes the other screens to start breaking. The workaround currently is to add a language which creates the organisation config and then other screens start working. Ideally Delete All should not delete Organisation Config row completely. It should keep it with English language. 
- A lot of data is not deleted (especially new tables such as task etc). From an older card, the following had to be done 
```
delete from catchment_address_mapping where catchment_id in (select id from catchment where organisation_id = 177);
delete from catchment where organisation_id = 177;
delete from location_location_mapping where organisation_id = 177;
delete from address_level where organisation_id = 177;
delete from gender where organisation_id = 177;
delete from user_group where organisation_id = 177;
delete from groups where organisation_id = 177;
delete from user_review_matrix where organisation_id = 177;
delete from users where organisation_id = 177;
delete from organisation where id = 177;
```
- ETL tables are not dropped.

**Comment by vinayvenu** [comment]
This is required when
1. we need to take an existing implementation from an organisation and isolate it to be deployed on an in-premise setup
2. we need to clean up old organisations

**Comment by petmongrels** [comment]
Some related issues may have been fixed here - https://github.com/avniproject/avni-server/issues/722

**Comment by himeshr** [comment]
As part of Deletion of Metadata, i'm also cleaning up the ETL schema and ETL data for the org.
But we arent disabling the ETL job, as the trigger is in avni_etl DB, which isn't accessible from avni-server code.

**Comment by 1t5j0y** [comment]
Don't we need a save for the user after updating sync settings [here](https://github.com/avniproject/avni-server/blob/6ab9eb93dca9de5132cdeef103f07be88fcea7c5/avni-server-api/src/main/java/org/avni/server/service/OrganisationService.java#L840) ?

**Comment by himeshr** [comment]
> Don't we need a save for the user after updating sync settings [here](https://github.com/avniproject/avni-server/blob/6ab9eb93dca9de5132cdeef103f07be88fcea7c5/avni-server-api/src/main/java/org/avni/server/service/OrganisationService.java#L840) ?

Should be fine, as we are performing update of a mangaged entity within a transaction.. as specified here
https://medium.com/@padiahrohit/publishing-domain-events-spring-data-5075505f3f27#:~:text=But%20if%20you%E2%80%99re,automatically%20and%20persists.

**Comment by AchalaBelokar** [comment]
- [ ]Login with maha@apf1  and try to delete it
- [x] when organisation  is prod type are showing error production organisation's data cannot be deleted.
- [ ] after selected both checkbox I started and after 2.9 min it is showing me error and second time it is showing 3.2 min error  network error
- [ ] then I selected only one check box still showing same error

**Comment by himeshr** [comment]
@AchalaBelokar pls check now

**Comment by himeshr** [comment]
@AchalaBelokar Have specified list of db tables that are supposed to be cleaned up as part of OrgDataDeletion.
Refer to https://avni.readme.io/docs/avni-server-db-changes#definition-for-classification-of-avni-db-tables-into-types readme doc for classification info of the tables across segments of transactional /metadata and adminConfig data.
[OrgDataDeletionCheckInDB.txt](https://github.com/user-attachments/files/16659796/OrgDataDeletionCheckInDB.txt)

**Comment by himeshr** [comment]
Failure reported for following instance.. During deletion of org data for apftestach org in staging environment
```
Caused by: org.postgresql.util.PSQLException: ERROR: update or delete on table "form" violates foreign key constraint "decision_concept_form" on table "decision_concept"
  Detail: Key is still referenced from table "decision_concept".
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2270)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1998)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:255)
        at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:570)
        at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:420)
        at org.postgresql.jdbc2.AbstractJdbc2Statement.executeUpdate(AbstractJdbc2Statement.java:366)
        at sun.reflect.GeneratedMethodAccessor409.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:114)
        at com.sun.proxy.$Proxy121.executeUpdate(Unknown Source)
        at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:175)
        ... 149 common frames omitted
```
@AchalaBelokar Create a new bug card for this and assign it to me.. Since this card has already been delivered, we'll not re-open this now.
